"""룰베이스 파서 결과 검증 LLM 레이어 (Parse Fidelity Validator).

규칙 기반 파서(_parse_rule_based_strategy)가 사용자의 원문 의도를 올바르게 해석했는지
LLM으로 재확인한다. 이 레이어는 **새 전략을 만들지 않는다** — 원문과 파싱 결과를 비교해
누락/모호/실행불가/과잉추론을 찾아내고, 명백한 파싱 오류만 교정한다.

설계 원칙:
- 항상 인라인 실행(룰 파스 성공 직후). 단, LLM이 닿지 않으면 즉시 graceful degrade해서
  빠른 경로(룰 파스 즉답)를 절대 막지 않는다. 테스트/CI(서버 없음)에서는 probe가 즉시
  실패해 원본을 그대로 반환한다.
- correctedStrategy는 ParsedStrategy 스키마로 검증될 때만 자동 적용한다(환각 방어).
  적용 시에도 원문 description은 보존한다.
- 투자 자문/추천/성능 개선은 하지 않는다(규제 안전). 검증·교정·되묻기만 한다.

기존 Rule Parse Guard(_consult_rule_parse_guard, accept/reject 이진 판정)와 달리,
이 레이어는 사용자에게 보여줄 구조화된 검증 리포트(issues/clarifications 등)를 만든다.
"""

from __future__ import annotations

import json
import logging
import os
import time
from typing import List, Literal, Optional

from pydantic import BaseModel, Field, ValidationError

from llm_backend import OLLAMA_BASE_URL, ollama_auth_headers

logger = logging.getLogger(__name__)

# LLM 호출 예산. 룰 파스 즉답을 막지 않도록 짧게 유지한다.
_VALIDATION_PROBE_TIMEOUT_S = 3.0   # LLM 도달 가능성 probe(GET /api/tags) — refused/cold면 즉시 degrade
_VALIDATION_TIMEOUT_S = 120         # 단일 생성 호출(워밍업된 서버 ~9s). 재시도 없음.
# 파싱 본경로(_OLLAMA_NUM_CTX=16384)와 반드시 같은 값 유지 — num_ctx가 다르면 Ollama가
# 러너를 재시작해 호출마다 콜드 페널티가 붙는다.
_VALIDATION_NUM_CTX = 16384
# 출력 계약이 diff(correctedFields, 바뀐 필드만)라 전체 전략 재출력이 없다. 유효 판정은
# {"isValid":true,"confidence":..} 한 줄이면 끝 — 생성 토큰이 검증 지연의 지배 항이라
# 여기를 줄이는 것이 곧 시간 단축이다.
_VALIDATION_NUM_PREDICT = 1024


# ─── 검증 리포트 스키마 (사용자 지정 계약, camelCase 그대로) ────────────────────

class ParseValidationIssue(BaseModel):
    field: str = ""
    severity: Literal["error", "warning"] = "warning"
    message: str = ""


class ParseValidationReport(BaseModel):
    """룰베이스 파싱 결과에 대한 LLM 검증 리포트.

    프론트로 그대로 전달되는 계약이므로 필드명은 사용자가 지정한 camelCase를 유지한다.
    """

    isValid: bool = True
    confidence: float = 0.0
    correctedStrategy: Optional[dict] = None
    # LLM 출력 계약(부분 diff): 바뀌어야 하는 필드만 담는다. 서버가 원본과 병합해
    # correctedStrategy(전체 객체)를 채우므로 하류 계약은 그대로 유지된다.
    correctedFields: Optional[dict] = None
    issues: List[ParseValidationIssue] = Field(default_factory=list)
    missingFields: List[str] = Field(default_factory=list)
    clarificationQuestions: List[str] = Field(default_factory=list)
    userFacingMessage: str = ""


PARSE_VALIDATION_PROMPT = """You are a strategy validation layer for an investment strategy builder.

Your role is NOT to create a new strategy.
Your role is to validate whether the rule-based parser correctly interpreted the user's original input.

You must compare:
1. The user's original natural language input (Korean)
2. The parsed strategy object generated by the rule-based parser

Check the following:
- Whether the parsed result matches the user's intent
- Whether required fields are missing
- Whether any condition is ambiguous
- Whether any condition is impossible to execute
- Whether the parser inferred something not stated by the user
- Whether the strategy is ready for backtesting

You must not provide investment advice.
You must not recommend stocks, assets, timing, or parameters.
You must not improve the strategy for performance.
You may only validate, correct obvious parsing errors, or ask clarification questions.

The parsed strategy object follows this schema (ParsedStrategy):
- description: string (original user text, must be preserved verbatim)
- universe: array of "KOSPI" | "KOSDAQ" | "KOSPI200"
- sector: Korean sector name restricting the universe to one industry
    (e.g. "반도체", "이차전지", "바이오/제약", "게임") | null
- fundamental_filters: array of {metric, operator(<,>,<=,>=), value}
    metric ∈ per, pbr, psr, pcr, ev_ebitda, roe_or_gpa, roa, debt_ratio, current_ratio, quick_ratio,
    reserve_ratio, net_margin, gross_margin, operating_margin, revenue_growth,
    operating_income_growth, net_income_growth, market_cap, trading_value,
    dividend_yield(배당수익률 %), payout_rate(배당성향 %), dividend_growth(배당성장률 %, 전년比),
    eps(주당순이익 원 — "흑자 기업"=eps>0, "적자 제외"=eps>0, "적자 기업"=eps<0),
    ebit(영업이익 억원 — "영업이익 흑자"=ebit>0, "영업이익 적자"=ebit<0; 영업이익증가율/영업이익률로 바꿔 해석 금지),
    net_income(당기순이익 억원),
    operating_cf_amount/investing_cf_amount/financing_cf_amount(영업·투자·재무활동 현금흐름 억원 —
      증가율은 ocf_growth/fcf_growth로, 절대 금액과 혼동 금지. 투자·재무는 통상 음수)
- entry_signals / exit_signals: array of {indicator, signal_type(buy/sell), ...params}
    indicator ∈ ma_crossover, rsi, ema, macd, bollinger_bands, breakout, volume_spike,
    stochastic, cci, adx, williams_r, mfi, roc, ai_model, ai_drop_model
    (williams_r=Williams %R -100~0, mfi=Money Flow Index 0~100, roc=Rate of Change/모멘텀 %)
- ranking_metric: "return" | null
- max_positions, hold_period_days, rebalancing_period, stop_loss_pct, take_profit_pct,
  trailing_stop_pct, max_mdd_limit_pct, backtest_start_date, backtest_end_date

NOTE: the parsed JSON you receive omits null/unset fields to stay short — a field that is
absent from the JSON is null.

The user's original input may contain typos or misspellings. Interpret by intent, not by
surface characters. If the rule-based parser missed a value because of a typo, correct it
(e.g. Korean "5게" is a typo for "5개" = 5 stocks = max_positions 5; "손졀" = "손절").

Return ONLY valid JSON, no prose.

If the parse already faithfully matches the user's intent, return EXACTLY this and nothing more:
{"isValid": true, "confidence": number}

Otherwise return:
{
  "isValid": boolean,
  "confidence": number,           // 0.0–1.0, your confidence that the parse matches intent
  "correctedFields": object | null,
  "issues": [
    { "field": string, "severity": "error" | "warning", "message": string }
  ],
  "missingFields": string[],
  "clarificationQuestions": string[],
  "userFacingMessage": string
}

Rules for correctedFields:
- It is a PARTIAL object: include ONLY the fields whose parsed value must change, with their
  corrected values. Never repeat fields the parser already got right. NEVER output the whole
  strategy object.
- Provide it ONLY when the parser made an obvious, unambiguous interpretation error
  (e.g. user said 손절 5% but parser stored take_profit_pct=5, or a typo caused a missed field).
  Otherwise set it to null and use issues/clarificationQuestions instead.
- To clear a misassigned field, include it with null
  (e.g. {"take_profit_pct": null, "stop_loss_pct": 5}).
- Array fields (entry_signals, exit_signals, fundamental_filters, universe) are replaced as a
  whole: if one needs correction, include the complete corrected array.
- If the user restricted the scope to one industry (e.g. "반도체 중심으로", "2차전지 위주로",
  "바이오 쪽만") but the parsed JSON has no `sector`, that is a missed field — include
  {"sector": <Korean sector name>}. Correct an obvious typo when mapping (e.g. "재약주" →
  "제약주" → "바이오/제약"). Do NOT invent a sector the user did not mention.
- Never include `description`.
- Never add conditions the user did not state. Never tune values for performance.
- Never add entry_signals or exit_signals the user did not explicitly mention. In particular,
  never introduce ai_model / ai_drop_model unless the user's text literally mentions
  "AI" or "인공지능". A ranking strategy (ranking_metric) needs no entry signal.

Write `issues[].message`, `clarificationQuestions`, and `userFacingMessage` in Korean.
Keep `userFacingMessage` short and neutral (no advice, no recommendation)."""


def build_validation_user_message(user_input: str, parsed_dump: dict) -> str:
    """원문 + 파싱 결과 JSON을 비교용 메시지로 합친다."""
    return (
        f"사용자 원문 입력:\n\"{user_input}\"\n\n"
        f"규칙 기반 파서가 생성한 전략 객체(JSON):\n"
        f"{json.dumps(parsed_dump, ensure_ascii=False)}\n\n"
        f"위 파싱 결과가 원문 의도를 올바르게 반영했는지 검증하고 스키마에 맞는 JSON만 출력하세요."
    )


def validate_parse(parser, user_input: str, parsed):
    """룰베이스 파싱 결과를 LLM으로 검증한다.

    반환: (적용본 ParsedStrategy, 리포트 dict).
    LLM이 닿지 않거나 어떤 단계든 실패하면 원본 parsed와 skipped 리포트를 돌려준다
    (빠른 경로를 깨지 않는다).
    """
    from engine.nl_parser import ParsedStrategy, _parse_model_json_response

    started = time.perf_counter()
    try:
        raw = _run_validation_llm(
            parser,
            PARSE_VALIDATION_PROMPT,
            # null 필드는 빼고 보낸다(입력 토큰 절감) — 프롬프트가 '누락=null'을 명시한다.
            build_validation_user_message(user_input, parsed.model_dump(exclude_none=True)),
        )
        if not raw:
            return parsed, _skipped_report()
        report = _parse_model_json_response(raw, ParseValidationReport)
    except Exception as exc:  # noqa: BLE001 — 검증은 best-effort, 실패는 빠른 경로를 깨지 않는다
        logger.warning("parse validation skipped | input=%r err=%r", user_input[:80], exc)
        return parsed, _skipped_report()

    corrected = _maybe_apply_correction(parser, parsed, report, ParsedStrategy, user_input)
    logger.info(
        "parse validation | isValid=%s confidence=%.2f corrected=%s issues=%d took_ms=%d | input=%r",
        report.isValid, report.confidence, corrected is not parsed, len(report.issues),
        round((time.perf_counter() - started) * 1000), user_input[:80],
    )
    return corrected, report.model_dump()


def _maybe_apply_correction(parser, parsed, report: ParseValidationReport, parsed_strategy_cls, user_input: str):
    """교정(diff 또는 전체 객체)이 스키마로 검증되면 자동 적용한다(원문 description 보존).

    1차 계약은 correctedFields(부분 diff) — LLM이 바뀐 필드만 출력하므로 전체 전략 재출력
    대비 생성 토큰이 크게 준다(검증 지연의 지배 항). 원본 dump에 병합해 전체 후보를 만들고,
    검증 통과 시 report.correctedStrategy에 병합본을 채워 하류 계약을 유지한다.
    구계약(correctedStrategy 전체 객체)도 하위호환으로 수용한다.

    검증 실패 시 원본을 유지하고 리포트의 correctedStrategy/correctedFields를 null로 비워
    프론트가 잘못된 교정본을 표시하지 않게 한다.

    스키마 검증만으로는 환각을 못 막는다 — 교정 LLM이 사용자가 언급하지 않은 신호
    (예: ai_model 'AI 매수 예측')를 스키마에 맞게 끼워 넣으면 그대로 통과한다. 그래서
    LLM 파싱 본경로와 동일한 기준(_validate_signals: 이름 고정 지표는 원문에 그 키워드가
    있어야 인정)으로 교정본의 진입/청산 신호를 재검증해, 환각 신호만 떨구고 나머지 교정은
    유지한다.
    """
    diff = report.correctedFields
    if isinstance(diff, dict) and diff:
        known = set(parsed_strategy_cls.model_fields)
        # description은 사용자 원문이라 교정 대상이 아니고, 미지 필드는 스키마 검증 전에 걸러
        # diff 전체가 무효화되는 것을 막는다.
        cleaned = {k: v for k, v in diff.items() if k in known and k != "description"}
        candidate_dump = {**parsed.model_dump(), **cleaned} if cleaned else None
    else:
        candidate_dump = report.correctedStrategy
    if not isinstance(candidate_dump, dict) or not candidate_dump:
        report.correctedFields = None
        return parsed
    try:
        candidate = parsed_strategy_cls.model_validate(candidate_dump)
    except ValidationError as exc:
        logger.warning("corrected parse invalid, keeping original | err=%r", exc)
        report.correctedStrategy = None
        report.correctedFields = None
        return parsed
    # 원문 설명은 사용자 입력이므로 LLM이 바꿔도 무시하고 보존한다.
    candidate.description = parsed.description
    from engine.nl_parser import _extract_explicit_universe, _validate_signals

    validated_entry = _validate_signals(list(candidate.entry_signals), user_input)
    validated_exit = _validate_signals(list(candidate.exit_signals), user_input)
    dropped = (len(candidate.entry_signals) - len(validated_entry)) + (
        len(candidate.exit_signals) - len(validated_exit)
    )
    if dropped:
        logger.warning(
            "correctedStrategy hallucinated %d signal(s), stripped | input=%r",
            dropped, user_input[:80],
        )
        candidate.entry_signals = validated_entry
        candidate.exit_signals = validated_exit
    # 유니버스는 순수 어휘 매핑(KOSPI/KOSDAQ/KOSPI200)이라 교정 LLM이 개선할 여지가 없다 —
    # 실사례: "KOSPI 대형주"(→KOSPI200)를 교정본이 그대로 "KOSPI"로 되돌려 유니버스가
    # 200종목에서 전체 코스피(800+)로 확대되며 백테스트가 크게 느려짐. max_positions 등
    # 숫자 필드는 교정 LLM이 원본 파싱 실수를 고칠 수 있어야 하므로 여기서 강제하지 않는다.
    explicit_universe = _extract_explicit_universe(user_input)
    if explicit_universe is not None:
        candidate.universe = explicit_universe
    report.correctedStrategy = candidate.model_dump()
    return candidate


def _skipped_report() -> dict:
    """LLM 미가용/실패 시 빠른 경로를 깨지 않는 중립 리포트."""
    return ParseValidationReport(isValid=True, confidence=0.0).model_dump()


def _run_validation_llm(parser, system_prompt: str, user_message: str) -> Optional[str]:
    """검증용 LLM 호출. ollama는 단일 POST(재시도 없음), mlx는 로컬 chat.

    ollama 경로는 먼저 짧은 GET probe로 도달 가능성을 확인한다 — refused(서버 없음)나
    cold(미응답)면 즉시 None을 반환해 빠른 경로를 막지 않는다. 닿으면 단일 /api/chat를
    호출한다(워밍업된 서버는 ~9s). 콜드스타트 장기 재시도(parse 본경로의 320s 예산)는
    검증 같은 보조 기능에는 쓰지 않는다.

    NL_VALIDATOR_MODEL(env)로 검증 전용 경량 모델을 지정할 수 있다(ollama 경로만).
    검증은 '비교+판정' 과제라 파싱 본경로보다 작은 모델로 충분할 수 있다 — 단, 별도
    모델은 Ollama에 추가 로드되므로 메모리 여유가 있을 때만 opt-in.
    """
    import urllib.request

    if getattr(parser, "backend", "ollama") == "mlx":
        return parser.chat(system_prompt, user_message, max_tokens=_VALIDATION_NUM_PREDICT, temperature=0.0)

    if not _ollama_reachable():
        return None

    body = json.dumps({
        "model": os.environ.get("NL_VALIDATOR_MODEL", "").strip() or parser.ollama_model,
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_message},
        ],
        "stream": False,
        "think": False,
        "format": "json",
        "options": {
            "temperature": 0,
            "num_ctx": _VALIDATION_NUM_CTX,
            "num_predict": _VALIDATION_NUM_PREDICT,
        },
    }).encode()
    req = urllib.request.Request(
        f"{OLLAMA_BASE_URL}/api/chat",
        data=body,
        headers={"Content-Type": "application/json", **ollama_auth_headers()},
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=_VALIDATION_TIMEOUT_S) as resp:
        data = json.loads(resp.read())
    return (data.get("message") or {}).get("content", "")


def _ollama_reachable(timeout: float = _VALIDATION_PROBE_TIMEOUT_S) -> bool:
    """본문 없는 GET /api/tags로 LLM 도달 가능성을 빠르게 확인한다.

    서버 없음(connection refused)이면 즉시 예외 → False. 워밍업된 서버면 즉시 200 → True.
    """
    import urllib.request

    try:
        req = urllib.request.Request(
            f"{OLLAMA_BASE_URL}/api/tags", headers=ollama_auth_headers(), method="GET"
        )
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            resp.read()
        return True
    except Exception:
        return False
