"""룰베이스 파서 결과 검증 LLM 레이어 (Parse Fidelity Validator).

규칙 기반 파서(_parse_rule_based_strategy)가 사용자의 원문 의도를 올바르게 해석했는지
LLM으로 재확인한다. 이 레이어는 **새 전략을 만들지 않는다** — 원문과 파싱 결과를 비교해
누락/모호/실행불가/과잉추론을 찾아내고, 명백한 파싱 오류만 교정한다.

설계 원칙:
- 항상 인라인 실행(룰 파스 성공 직후). 단, LLM이 닿지 않으면 즉시 graceful degrade해서
  빠른 경로(룰 파스 즉답)를 절대 막지 않는다. 테스트/CI(서버 없음)에서는 probe가 즉시
  실패해 원본을 그대로 반환한다.
- correctedStrategy는 ParsedStrategy 스키마로 검증될 때만 자동 적용한다(환각 방어).
  적용 시에도 원문 description은 보존한다.
- 투자 자문/추천/성능 개선은 하지 않는다(규제 안전). 검증·교정·되묻기만 한다.

기존 Rule Parse Guard(_consult_rule_parse_guard, accept/reject 이진 판정)와 달리,
이 레이어는 사용자에게 보여줄 구조화된 검증 리포트(issues/clarifications 등)를 만든다.
"""

from __future__ import annotations

import json
import logging
from typing import List, Literal, Optional

from pydantic import BaseModel, Field, ValidationError

from llm_backend import OLLAMA_BASE_URL, ollama_auth_headers

logger = logging.getLogger(__name__)

# LLM 호출 예산. 룰 파스 즉답을 막지 않도록 짧게 유지한다.
_VALIDATION_PROBE_TIMEOUT_S = 3.0   # LLM 도달 가능성 probe(GET /api/tags) — refused/cold면 즉시 degrade
_VALIDATION_TIMEOUT_S = 120         # 단일 생성 호출(워밍업된 서버 ~9s). 재시도 없음.
_VALIDATION_NUM_CTX = 16384         # system prompt + parsed JSON가 기본 num_ctx(4096)를 넘는다
_VALIDATION_NUM_PREDICT = 2048      # correctedStrategy + issues 출력 여유


# ─── 검증 리포트 스키마 (사용자 지정 계약, camelCase 그대로) ────────────────────

class ParseValidationIssue(BaseModel):
    field: str = ""
    severity: Literal["error", "warning"] = "warning"
    message: str = ""


class ParseValidationReport(BaseModel):
    """룰베이스 파싱 결과에 대한 LLM 검증 리포트.

    프론트로 그대로 전달되는 계약이므로 필드명은 사용자가 지정한 camelCase를 유지한다.
    """

    isValid: bool = True
    confidence: float = 0.0
    correctedStrategy: Optional[dict] = None
    issues: List[ParseValidationIssue] = Field(default_factory=list)
    missingFields: List[str] = Field(default_factory=list)
    clarificationQuestions: List[str] = Field(default_factory=list)
    userFacingMessage: str = ""


PARSE_VALIDATION_PROMPT = """You are a strategy validation layer for an investment strategy builder.

Your role is NOT to create a new strategy.
Your role is to validate whether the rule-based parser correctly interpreted the user's original input.

You must compare:
1. The user's original natural language input (Korean)
2. The parsed strategy object generated by the rule-based parser

Check the following:
- Whether the parsed result matches the user's intent
- Whether required fields are missing
- Whether any condition is ambiguous
- Whether any condition is impossible to execute
- Whether the parser inferred something not stated by the user
- Whether the strategy is ready for backtesting

You must not provide investment advice.
You must not recommend stocks, assets, timing, or parameters.
You must not improve the strategy for performance.
You may only validate, correct obvious parsing errors, or ask clarification questions.

The parsed strategy object follows this schema (ParsedStrategy):
- description: string (original user text, must be preserved verbatim)
- universe: array of "KOSPI" | "KOSDAQ" | "KOSPI200"
- fundamental_filters: array of {metric, operator(<,>,<=,>=), value}
    metric ∈ per, pbr, psr, roe_or_gpa, roa, debt_ratio, current_ratio, quick_ratio,
    reserve_ratio, net_margin, gross_margin, revenue_growth, operating_income_growth,
    net_income_growth, market_cap, trading_value
- entry_signals / exit_signals: array of {indicator, signal_type(buy/sell), ...params}
    indicator ∈ ma_crossover, rsi, ema, macd, bollinger_bands, breakout, volume_spike,
    stochastic, cci, adx, ai_model, ai_drop_model
- ranking_metric: "return" | null
- max_positions, hold_period_days, rebalancing_period, stop_loss_pct, take_profit_pct,
  trailing_stop_pct, max_mdd_limit_pct, backtest_start_date, backtest_end_date

The user's original input may contain typos or misspellings. Interpret by intent, not by
surface characters. If the rule-based parser missed a value because of a typo, correct it
(e.g. Korean "5게" is a typo for "5개" = 5 stocks = max_positions 5; "손졀" = "손절").

Rules for correctedStrategy:
- Provide it ONLY when the parser made an obvious, unambiguous interpretation error
  (e.g. user said 손절 5% but parser stored take_profit_pct=5, or a typo caused a missed field).
- It must be a COMPLETE ParsedStrategy object in the exact schema above, keeping every
  field the parser got right and fixing only the misread field.
- Keep `description` exactly as the parser had it.
- If the parse is already faithful, set correctedStrategy to null.
- Never add conditions the user did not state. Never tune values for performance.

Return ONLY valid JSON, no prose, following this exact schema:
{
  "isValid": boolean,
  "confidence": number,           // 0.0–1.0, your confidence that the parse matches intent
  "correctedStrategy": object | null,
  "issues": [
    { "field": string, "severity": "error" | "warning", "message": string }
  ],
  "missingFields": string[],
  "clarificationQuestions": string[],
  "userFacingMessage": string
}

Write `issues[].message`, `clarificationQuestions`, and `userFacingMessage` in Korean.
Keep `userFacingMessage` short and neutral (no advice, no recommendation)."""


def build_validation_user_message(user_input: str, parsed_dump: dict) -> str:
    """원문 + 파싱 결과 JSON을 비교용 메시지로 합친다."""
    return (
        f"사용자 원문 입력:\n\"{user_input}\"\n\n"
        f"규칙 기반 파서가 생성한 전략 객체(JSON):\n"
        f"{json.dumps(parsed_dump, ensure_ascii=False)}\n\n"
        f"위 파싱 결과가 원문 의도를 올바르게 반영했는지 검증하고 스키마에 맞는 JSON만 출력하세요."
    )


def validate_parse(parser, user_input: str, parsed):
    """룰베이스 파싱 결과를 LLM으로 검증한다.

    반환: (적용본 ParsedStrategy, 리포트 dict).
    LLM이 닿지 않거나 어떤 단계든 실패하면 원본 parsed와 skipped 리포트를 돌려준다
    (빠른 경로를 깨지 않는다).
    """
    from engine.nl_parser import ParsedStrategy, _parse_model_json_response

    try:
        raw = _run_validation_llm(
            parser,
            PARSE_VALIDATION_PROMPT,
            build_validation_user_message(user_input, parsed.model_dump()),
        )
        if not raw:
            return parsed, _skipped_report()
        report = _parse_model_json_response(raw, ParseValidationReport)
    except Exception as exc:  # noqa: BLE001 — 검증은 best-effort, 실패는 빠른 경로를 깨지 않는다
        logger.warning("parse validation skipped | input=%r err=%r", user_input[:80], exc)
        return parsed, _skipped_report()

    corrected = _maybe_apply_correction(parser, parsed, report, ParsedStrategy)
    logger.info(
        "parse validation | isValid=%s confidence=%.2f corrected=%s issues=%d | input=%r",
        report.isValid, report.confidence, corrected is not parsed, len(report.issues), user_input[:80],
    )
    return corrected, report.model_dump()


def _maybe_apply_correction(parser, parsed, report: ParseValidationReport, parsed_strategy_cls):
    """correctedStrategy가 스키마로 검증되면 자동 적용한다(원문 description 보존).

    검증 실패 시 원본을 유지하고 리포트의 correctedStrategy를 null로 비워 프론트가 잘못된
    교정본을 표시하지 않게 한다.
    """
    candidate_dump = report.correctedStrategy
    if not isinstance(candidate_dump, dict) or not candidate_dump:
        return parsed
    try:
        candidate = parsed_strategy_cls.model_validate(candidate_dump)
    except ValidationError as exc:
        logger.warning("correctedStrategy invalid, keeping original parse | err=%r", exc)
        report.correctedStrategy = None
        return parsed
    # 원문 설명은 사용자 입력이므로 LLM이 바꿔도 무시하고 보존한다.
    candidate.description = parsed.description
    report.correctedStrategy = candidate.model_dump()
    return candidate


def _skipped_report() -> dict:
    """LLM 미가용/실패 시 빠른 경로를 깨지 않는 중립 리포트."""
    return ParseValidationReport(isValid=True, confidence=0.0).model_dump()


def _run_validation_llm(parser, system_prompt: str, user_message: str) -> Optional[str]:
    """검증용 LLM 호출. ollama는 단일 POST(재시도 없음), mlx는 로컬 chat.

    ollama 경로는 먼저 짧은 GET probe로 도달 가능성을 확인한다 — refused(서버 없음)나
    cold(미응답)면 즉시 None을 반환해 빠른 경로를 막지 않는다. 닿으면 단일 /api/chat를
    호출한다(워밍업된 서버는 ~9s). 콜드스타트 장기 재시도(parse 본경로의 320s 예산)는
    검증 같은 보조 기능에는 쓰지 않는다.
    """
    import urllib.request

    if getattr(parser, "backend", "ollama") == "mlx":
        return parser.chat(system_prompt, user_message, max_tokens=_VALIDATION_NUM_PREDICT, temperature=0.0)

    if not _ollama_reachable():
        return None

    body = json.dumps({
        "model": parser.ollama_model,
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_message},
        ],
        "stream": False,
        "think": False,
        "format": "json",
        "options": {
            "temperature": 0,
            "num_ctx": _VALIDATION_NUM_CTX,
            "num_predict": _VALIDATION_NUM_PREDICT,
        },
    }).encode()
    req = urllib.request.Request(
        f"{OLLAMA_BASE_URL}/api/chat",
        data=body,
        headers={"Content-Type": "application/json", **ollama_auth_headers()},
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=_VALIDATION_TIMEOUT_S) as resp:
        data = json.loads(resp.read())
    return (data.get("message") or {}).get("content", "")


def _ollama_reachable(timeout: float = _VALIDATION_PROBE_TIMEOUT_S) -> bool:
    """본문 없는 GET /api/tags로 LLM 도달 가능성을 빠르게 확인한다.

    서버 없음(connection refused)이면 즉시 예외 → False. 워밍업된 서버면 즉시 200 → True.
    """
    import urllib.request

    try:
        req = urllib.request.Request(
            f"{OLLAMA_BASE_URL}/api/tags", headers=ollama_auth_headers(), method="GET"
        )
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            resp.read()
        return True
    except Exception:
        return False
