import os
import polars as pl
import pandas as pd
import numpy as np
from datetime import datetime
from tqdm import tqdm
import glob

# Ensure we can import from backend/engine
import sys
sys.path.append(os.path.join(os.getcwd(), 'backend'))
from engine.indicators import IndicatorEngine

import argparse

def extract_training_data(ohlcv_dir, output_file, lookback_window=60, symbols=None, buy_threshold=0.07, sell_threshold=0.07):
    """
    Extracts OHLCV and technical indicators for a set of symbols and saves them to a parquet file for training.
    """
    if not symbols:
        # Get top 200 list if exists, else take all parquet files
        if os.path.exists('top200.txt'):
            with open('top200.txt', 'r') as f:
                content = f.read().strip()
                if content.startswith('[') and content.endswith(']'):
                    import json
                    symbols = json.loads(content)
                else:
                    symbols = [line.strip() for line in content.split('\n') if line.strip()]
        else:
            symbols = [os.path.basename(f).replace('.parquet', '') for f in glob.glob(os.path.join(ohlcv_dir, '*.parquet'))]

    all_data = []
    
    # Common indicator requirements for training
    base_conditions = [
        {'id': 'ma_crossover', 'params': {'short': 5, 'long': 20}},
        {'id': 'rsi', 'params': {'period': 14}},
        {'id': 'bollinger_bands', 'params': {'period': 20}},
        {'id': 'volume_spike', 'params': {'period': 20}}
    ]

    print(f"Extracting data for {len(symbols)} symbols...")
    print(f"Targets: BuyThreshold={buy_threshold*100}%, SellThreshold={sell_threshold*100}%")
    
    for symbol in tqdm(symbols):
        try:
            file_path = os.path.join(ohlcv_dir, f"{symbol}.parquet")
            if not os.path.exists(file_path):
                continue
                
            df_pl = pl.read_parquet(file_path)
            
            # 1. Calculate Indicators
            df_pl = IndicatorEngine.calculate(df_pl, base_conditions)
            
            # 2. Conversion & Preprocessing
            pdf = df_pl.to_pandas()
            pdf['symbol'] = symbol
            pdf = pdf.sort_values('date')
            
            # 3. Labeling: Future Returns (Next 10 days max return)
            # Use provided targets
            pdf['fwd_return_10'] = pdf['close'].shift(-10) / pdf['close'] - 1
            
            # Binary targets for XGBoost
            pdf['target_up'] = (pdf['close'].rolling(window=10).max().shift(-10) / pdf['close'] - 1 >= buy_threshold).astype(int)
            pdf['target_down'] = (pdf['close'].rolling(window=10).min().shift(-10) / pdf['close'] - 1 <= -sell_threshold).astype(int)
            
            # Keep old names for backward compatibility during transition if needed
            pdf['target_7pct_10d'] = pdf['target_up']
            pdf['target_drop_7pct_10d'] = pdf['target_down']
            
            # 4. Feature Engineering for Transformer
            # Scale prices to returns
            for col in ['open', 'high', 'low', 'close']:
                pdf[f'ret_{col}'] = pdf[col].pct_change()
            
            pdf['ret_volume'] = pdf['volume'].pct_change()
            
            # Drop NaN rows generated by pct_change and shift
            pdf_len_pre = len(pdf)
            pdf = pdf.dropna()
            if len(pdf) == 0:
                print(f"[DEBUG] {symbol}: All rows dropped after dropna. Pre-dropna rows: {pdf_len_pre}")
                print(f"[DEBUG] {symbol}: Null counts:\n{pdf_pl.null_count()}")
            
            if len(pdf) > lookback_window:
                all_data.append(pdf)
                
        except Exception as e:
            print(f"Error processing {symbol}: {e}")

    if all_data:
        final_df = pd.concat(all_data, ignore_index=True)
        final_df.to_parquet(output_file)
        print(f"Successfully saved {len(final_df)} bars for training to {output_file}")
    else:
        print("No data extracted.")

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--ohlcv_dir", default="/Users/eugene/nullalgo/simons/data/ohlcv")
    parser.add_argument("--output_file", default="/Users/eugene/nullalgo/simons/data/training_data_raw.parquet")
    parser.add_argument("--buy_threshold", type=float, default=0.07, help="Buy threshold (Target Upside Rate, e.g. 0.07 for 7%)")
    parser.add_argument("--sell_threshold", type=float, default=0.07, help="Sell threshold (Target Downside Rate, e.g. 0.07 for 7%)")
    args = parser.parse_args()
    
    os.makedirs(os.path.dirname(args.output_file), exist_ok=True)
    extract_training_data(args.ohlcv_dir, args.output_file, buy_threshold=args.buy_threshold, sell_threshold=args.sell_threshold)

